jwt:
  signature: songseonghuncandoanythingiwanttocompletethisprojectdonotlazyalldaysingsangssongbunniesfighting
  access:
    expiration: 3600000000 # 1시간
    header: Authorization
  refresh:
    expiration: 1209600000 # 2주
    header: Authorization-refresh

gemini:
  api:
    key: AIzaSyDhXaLJNxJy7uGtlAH3ii5bjsBnVAXDJvg
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent

gcs:
  bucket:
    name: mapory
    key: model-block-455013-s4-256166007e77.json
