jwt:
  signature: songseonghuncandoanythingiwanttocompletethisprojectdonotlazyalldaysingsangssongbunniesfighting
  access:
    expiration: 3600000000 # 1시간
    header: Authorization
  refresh:
    expiration: 1209600000 # 2주
    header: Authorization-refresh
